#!/usr/bin/env bash
# First-time Linux install. Do not edit this file per release — later versions
# arrive as update tar.gz via /admin/updates or `pnpm apply-update --file`.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

log() {
  echo "[myblog] $*"
}

die() {
  echo "[myblog] $*" >&2
  exit 1
}

[[ -f package.json && -d src ]] || die "请在解压后的程序目录运行（需要 package.json 与 src/）"

if ! command -v node >/dev/null 2>&1; then
  die "需要 Node.js ≥22。先安装：https://nodejs.org/"
fi
NODE_MAJOR="$(node -p "process.versions.node.split('.')[0]")"
if [[ "$NODE_MAJOR" -lt 22 ]]; then
  die "当前 Node 是 $(node -v)，需要 ≥22"
fi

if ! command -v pnpm >/dev/null 2>&1; then
  if command -v corepack >/dev/null 2>&1; then
    log "启用 corepack pnpm"
    corepack enable
    corepack prepare pnpm@11.24.0 --activate
  else
    die "找不到 pnpm。请安装 pnpm 11，或升级 Node 后使用 corepack"
  fi
fi

if [[ -r /proc/meminfo ]]; then
  MEM_KB="$(awk '/MemTotal:/ {print $2}' /proc/meminfo)"
  SWAP_KB="$(awk '/SwapTotal:/ {print $2}' /proc/meminfo)"
  if [[ "$MEM_KB" -lt 1500000 && "$SWAP_KB" -lt 500000 ]]; then
    log "内存约 $((MEM_KB / 1024))MB 且几乎没有 swap。1GB 机器构建前请先加 1～2GB swap，否则 next build 容易 OOM。"
  fi
fi

mkdir -p data
if [[ ! -f .env ]]; then
  cp .env.example .env
  log "已从 .env.example 复制 .env（pnpm setup 会写入密钥与管理员）"
fi

export NODE_OPTIONS="${NODE_OPTIONS:-} --max-old-space-size=768"

log "安装依赖（pnpm install --frozen-lockfile）"
pnpm install --frozen-lockfile

log "数据库迁移（prisma migrate deploy，不写入演示文章）"
pnpm exec prisma migrate deploy

log "生产构建"
pnpm build

log "首装完成。不要改这个脚本来发新版本。"
echo
echo "接下来："
echo "  1. pnpm setup          # 手设管理员和备份口令（只做一次）"
echo "  2. pm2 start ecosystem.config.cjs"
echo "  3. pm2 save && pm2 startup"
echo
echo "以后升级：Windows 上 pnpm pack:update，把 tar.gz 拿到服务器后二选一"
echo "  - 后台 /admin/updates → 导入 → 应用 → 立刻重启"
echo "  - pnpm apply-update --file ./myblog-update-xxx.tar.gz && pm2 restart myblog"
